services:
  postgres:
    image: postgres:latest
    container_name: postgres_market_app
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  market_app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres